version: '3'

services:
  postgres-database:
    container_name: "postgres-database"
    image: bitnami/postgresql:14.2.0
    restart: always
    environment:
      - POSTGRES_USER=potatoes
      - POSTGRES_PASSWORD=tomatoes
      - POSTGRES_DB=simple-etl
    ports:
      - '5432:5432'
    volumes:
      - simple-etl-pipeline:/var/lib/postgresql/data
    networks:
      - simple-etl
  postgres-dev-database:
    container_name: "postgres-dev-database"
    image: bitnami/postgresql:14.2.0
    restart: always
    environment:
      - POSTGRES_USER=potatoes
      - POSTGRES_PASSWORD=tomatoes
      - POSTGRES_DB=dev-etl
    ports:
      - '5433:5432'
    volumes:
      - simple-etl-pipeline:/var/lib/postgresql/data
    networks:
      - simple-etl
  etl-worker:
    container_name: "etl-worker"
    build: .
    image: simple-etl
    depends_on:
      - postgres-database
    env_file:
      - .env.dev
    networks:
      - simple-etl
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - node.name=ws-es-node
      - discovery.type=single-node
      - cluster.name=ws-es-data-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled='false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - simple-etl-pipeline:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - simple-etl
    depends_on:
      - postgres-database
networks:
  simple-etl:

volumes:
  simple-etl-pipeline:
    driver: local
